<script lang="ts">
  import { onMount } from "svelte";

  let text = '...';
  let show = '404';
  const quotes = [
    "Should you be here?",
    "I have a bad feeling about this.",
    "ROOOAAR",
    "insert funny text here",
    "twitch funny moments youtube search",
    "wth am i?",
    "bro u lost?",
    "have you played jedi fallen order? great game",
    "i use arch btw",
    "i love you... wrong person",
    "c++ hello world speedrun",
    "fortnite battlepass",
    "WOOOW",
    "not funny didn't laugh",
    "You know, Amy, anytime someone calls attention to the breaking of gender roles, it ultimately undermines the concept of gender equality by implying that this is an exception and not the status quo.",
    "who am i?",
    "Say my name.",
    "Better call Saul!",
    "somebody once told me",
    "shrek 1 is the best movie change my mind",
    "thank you markiplier",
    "thank you pewdiepie",
    "tseries can suck my :pleading_face:",
    "what the hell is an error 69?",
    "have you found all the easter eggs in this site?",
    "bro's lost lmao",
    "Luke, I am your father.",
    "i lost 4 hours just thinking random quotes lol",
    "beta testing available right now over xvideos.com!",
    "wanna see my duck duck DUCK I MEANT DUCK DUCK nvm",
    "DAMN YOU!",
    "why u here?",
    "Hello there.",
    "bleading edge software is kinda funny",
    "i rate wen peopel can not speel thing rights",
    "accurate",
    "pls mommy give me da JUICE",
    "'I still see your shadows in my room.' - Depressed boi",
    "life is overrated",
    "check this out: https://github.com/ValveSoftware/steam-for-linux/issues/1890 it's a goldmine",
    "there is an easter egg that displays 'Error 69' instead of 404",
    "I mean... Ducks are a great source of food.",
    "ithinkitsprettynormalforsomeonetonotusespaces",
    "bro's finding funny just F5'ing the page",
    "TO THE MOON",
    "i think gays are pretty straight when they are ask about sexuality lmao",
    "DANG IT",
    "i love you arch linux... i love you",
    "imagine going to a 404 page to see which is the quote of the day",
    "I sense good luck on you.",
    "I sense duck on you.",
    "shame on you, i wash my ass every time i poo.",
    "why people say 'you are welcome'?",
    "dumb question: do you still love me veronica??",
    "open-source software > close-source software",
    "github.com/_______",
    "im tired of writing quotes but i cant stop",
    "pls veronica come back to me",
    "nothing here. return later",
    "const life = null;",
    "let veronica = lover::new().thinkofher();",
    "I-I love my girlfriend",
    'Rawr',
    'Execute order 66',
    'wtf man?',
    'I sense great force in you',
    'You have become the very thing you swore to destroy.',
  ];

  const who_said = [
    'Dad',
    'Mom',
    'Luke Skywalker',
    'Anakin Skywalker',
    'Darth Vader',
    'Yoda',
    'Chewbacca',
    'Gerald',
    'Shrek',
    'Knuckles',
    'Sonic',
    'Shadow',
    'Garcello',
    'devkcud',
    'Amy',
    'Han Solo',
    'Pewdiepie',
    'Markiplier',
    'Ed Murphy',
    'Walter White',
    'Jesse Pinkman',
    'Cal Kestis',
    'Second Sister',
    'Ninth Sister',
    'Grue',
    'Gru',
    'Wreck-it, Ralph',
    'Donkey',
    'Lord Farquaad',
    'Fiona',
    'Peter Pan',
    'Magic Mirror',
    'Geppetto',
    'Robin Hood',
    'Princess Leia',
    'Boba Fett',
    'Palpatine',
    'Obi-Wan Kenobi',
    'Ben Kenobi',
    'C-3PO',
    'R2-D2',
    'Mario',
    'Wario',
    'Luigi',
    'Yoshi',
    'Waluigi',
    'Vanellope von Schweetz',
    'Zangief',
    'Chun-Li',
    'Ryu',
    'Ken',
    'Barbie',
    'Sticks',
    'Saul',
    'Jango Fett',
    'Jar Jar Binks',
  ];

  const emoji = [
    '💀',
    '😎',
    '🤗',
    '😑',
    '🥱',
    '🫠',
    '🤭',
    '🤤',
    '🤢',
    '🤮',
    '💩',
    '🤡',
    '👽',
    '😈',
    '🤠',
    '😱',
    '😭',
    '🥵',
    '🥶',
    '🤯',
    '🥺',
    '😩',
    '🤓',
    '🥰',
    '😘',
    '☺️',
    '😁',
    '😀',
    '😜',
    '😉',
    '🥸',
    '🙁',
    '😕',
    '😔',
    '😒',
    '🤪',
    '🥳',
    '😡',
    '😠',
    '😤',
    '😨',
    '🤫',
    '🤥',
    '🙄',
    '😬',
    '😐',
    '🤔',
    '🥴',
    '👊',
    '👍',
    '👎',
    '💪',
    '🫦',
    '💋',
    '👀',
    '🤝',
    '🖕',
  ];

  onMount(() => {
    quotes.push(`There is a total of ${quotes.length + 1} random quotes`);
    text = `${who_said[Math.floor(Math.random() * who_said.length)]}: ${quotes[Math.floor(Math.random() * quotes.length)]} ${emoji[Math.floor(Math.random() * emoji.length)]}`;
    show = Math.random() > 0.95 ? "69" : "404";
  });
</script>

<div style="height: calc(100vh - 2rem); display: flex; flex-direction: column; align-items: center; justify-content: center;">
  <h1 style="font-size: 60px; font-weight: 900;">Error {show}</h1>
  <p>Random quote:</p>
  <p style="text-align: center;">{text}</p>
</div>
